// <auto-generated />
using System;
using AbschlussKonzertKadetten.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AbschlussKonzertKadetten.Migrations
{
    [DbContext(typeof(KadettenContext))]
    [Migration("20180919121340_kadettinkader")]
    partial class kadettinkader
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AbschlussKonzertKadetten.Entity.Kadett", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<bool>("KadettInKader");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Kadett");
                });

            modelBuilder.Entity("AbschlussKonzertKadetten.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("AbschlussKonzertKadetten.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bemerkung");

                    b.Property<int>("ClientId");

                    b.Property<int>("KadettId");

                    b.Property<DateTime>("OrderDate");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("KadettId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("AbschlussKonzertKadetten.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Price");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("AbschlussKonzertKadetten.Models.TicketOrder", b =>
                {
                    b.Property<int>("OrderId");

                    b.Property<int>("TicketId");

                    b.Property<string>("Day");

                    b.Property<int>("Quantity");

                    b.HasKey("OrderId", "TicketId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketOrders");
                });

            modelBuilder.Entity("AbschlussKonzertKadetten.Models.Order", b =>
                {
                    b.HasOne("AbschlussKonzertKadetten.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AbschlussKonzertKadetten.Entity.Kadett", "Kadett")
                        .WithMany()
                        .HasForeignKey("KadettId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AbschlussKonzertKadetten.Models.TicketOrder", b =>
                {
                    b.HasOne("AbschlussKonzertKadetten.Models.Order", "Order")
                        .WithMany("TicketOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AbschlussKonzertKadetten.Models.Ticket", "Ticket")
                        .WithMany("TicketOrders")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
